# Generated by Django 3.1.3 on 2021-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_drop', models.BooleanField(default=False)),
            ],
        ),
    ]
