# Generated by Django 3.1.3 on 2021-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
