# Generated by Django 3.1.3 on 2021-04-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_testclass_array'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
