# Generated by Django 4.2.16 on 2024-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsandevents",
            name="summary_en",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="summary_ru",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
