# Generated by Django 4.2.16 on 2024-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_summary_en_course_summary_ru_course_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="summary_es",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="summary_fr",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_es",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_es",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_fr",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_fr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_fr",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
