# Generated by Django 4.0.8 on 2024-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_upload_file_alter_uploadvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='summary_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_en',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
